name: CI
on: 
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
      
    - name: Install libraries
      run: |
        pip install --upgrade pip
        pip install wheel
        pip install jupyter hypothesis
        pip install -U nbdev 
        pip install -Ue .
      
    - name: Attempt to read notebooks
      run: |
        nbdev_read_nbs
      
    - name: Check if notebooks are clean
      id: clean
      run: |
        nbdev_clean_nbs
        if [ -n "$(git status -uno -s)" ]; then
          echo "::error::Detected notebooks that are not cleaned."
          echo "\n\nList of notebooks that are not clean:"
          git status -s
          exit 1;
        fi
      
    - name: Check that library syncs with notebooks
      id: lib
      run: |
        nbdev_diff_nbs > _nbdev_diff_logs.txt
        if [ -n "$(cat _nbdev_diff_logs.txt)" ]; then 
          echo "::error::Detected notebooks that are not in sync with the library."
          cat _nbdev_diff_logs.txt
          if [[ $auto_fix == 'true' ]]; then 
            nbdev_build_lib
          fi
          exit 1;
        fi

    - name: Run tests
      run: |
        python -m unittest discover -s tests -v


